#define HOLD_ON_OTHER_KEY_PRESS
#define FORCE_NKRO
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define KEY_OVERRIDE_REPEAT_DELAY 200 // ms

#define OLED_TIMEOUT 10 * 1000 // 10 seconds

#define MK_3_SPEED // Mouse Constant mode
#define MK_MOMENTARY_ACCEL

// Unmodified
#define MK_C_OFFSET_UNMOD   8
#define MK_C_INTERVAL_UNMOD 6

// MS_ACL0
#define MK_C_OFFSET_0   2
#define MK_C_INTERVAL_0 6

// MS_ACL1
// #define MK_C_OFFSET_1   8
// #define MK_C_INTERVAL_1 6

// MS_ACL2
#define MK_C_OFFSET_2   26
#define MK_C_INTERVAL_2 6

// #define DEBUG_MATRIX_SCAN_RATE
// #define SERIAL_DEBUG

// #undef PRINTF_SUPPORT_DECIMAL_SPECIFIERS
// #define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1