#define HOLD_ON_OTHER_KEY_PRESS
#define FORCE_NKRO
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD


// #define DEBUG_MATRIX_SCAN_RATE

// #undef PRINTF_SUPPORT_DECIMAL_SPECIFIERS
// #define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1