#define HOLD_ON_OTHER_KEY_PRESS
#define FORCE_NKRO
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define KEY_OVERRIDE_REPEAT_DELAY 200 // ms

#define MOUSEKEY_INTERVAL  6
#define MOUSEKEY_MAX_SPEED 2

#define OLED_TIMEOUT 10 * 1000 // 10 seconds

// #define DEBUG_MATRIX_SCAN_RATE

// #undef PRINTF_SUPPORT_DECIMAL_SPECIFIERS
// #define PRINTF_SUPPORT_DECIMAL_SPECIFIERS 1